# Generated by Django 6.1 on 2026-08-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='repartidor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='enviado_cocina_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='listo_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('listo', 'Listo para servir'), ('servido', 'Servido'), ('cuenta', 'Cuenta solicitada'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mesero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('mesa', 'En el local'), ('delivery', 'Delivery'), ('llevar', 'Para llevar')], default='mesa', max_length=20),
        ),
    ]
