# Generated by Django 6.1 on 2026-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='componentes',
            field=models.TextField(blank=True, default='', help_text='Ingredientes o componentes del producto', verbose_name='Componentes/Ingredientes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen opcional del producto (formatos: JPG, PNG, WEBP)', null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
    ]
