# Generated by Django 6.1 on 2026-08-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cocina', 'Cocina'), ('caja', 'Caja'), ('entrega', 'Entregas'), ('limpieza', 'Limpieza')], default='mesero', max_length=20),
        ),
    ]
