# Generated by Django 6.1 on 2026-08-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('zona', models.CharField(blank=True, default='Salón principal', max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('limpieza', 'En limpieza')], default='disponible', max_length=20)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
