# Generated by Django 6.1 on 2026-08-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
        ('pedidos', '0002_remove_pedido_repartidor_pedido_enviado_cocina_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='zona',
        ),
        migrations.AddField(
            model_name='mesa',
            name='limpieza_completada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='limpieza_solicitada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='solicitada_limpieza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mesa',
            name='ultimo_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_usadas', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
